name: Build, deploy and release plugin

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create a GitHub release with this branch'
        default: true
        required: true
        type: boolean
      latest:
        description: 'Make release latest'
        default: true
        required: true
        type: boolean
      deploy:
        description: 'Deploy Gradle artifacts via SSH'
        default: true
        required: true
        type: boolean
      deploy-path:
        description: 'Path to deploy artifacts to'
        default: 'build'
        required: false
        type: string
  pull_request:
    branches:
      - master

jobs:
  master-deploy:
    uses: NeverMined-Entertainment/CI-CD/.github/workflows/master-deploy.yml@master
    with:
      release: ${{ (github.event_name == 'workflow_dispatch' && inputs.release) || (github.event_name == 'pull_request' && true) }}
      latest: ${{ (github.event_name == 'workflow_dispatch' && inputs.latest) || (github.event_name == 'pull_request' && true) }}
      deploy: ${{ (github.event_name == 'workflow_dispatch' && inputs.deploy) || (github.event_name == 'pull_request' && true) }}
      deploy-path: ${{ github.event_name == 'workflow_dispatch' && inputs['deploy-path'] || 'build' }}
    secrets:
      token: ${{ secrets.TOKEN }}
      ssh-host: ${{ secrets.SSH_HOST }}
      ssh-username: ${{ secrets.SSH_USERNAME }}
      ssh-password: ${{ secrets.SSH_PASSWORD }}
