name: Build, deploy and release plugin

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create a GitHub release with this PR'
        default: true
        required: false
        type: boolean
      latest:
        description: 'Make release latest'
        default: true
        required: false
        type: boolean
      deploy:
        description: 'Deploy Gradle artifacts via SSH'
        default: true
        required: false
        type: boolean
      deploy-path:
        description: 'Path to deploy artifacts to'
        default: 'build'
        required: false
        type: string
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '16'

      #      - name: Cache Gradle dependencies
      #        uses: actions/cache@v4
      #        with:
      #          path: ~/.gradle/caches
      #          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #          restore-keys: gradle-${{ runner.os }}-

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

  #      - name: Upload Build Artifact
  #        uses: actions/upload-artifact@v4
  #        with:
  #          path: build/libs/*.jar

  deploy:
    needs: build
    if: inputs.deploy == true
    runs-on: self-hosted

    steps:
      - name: Deploy via SSH
        uses: garygrossgarten/github-action-scp@0.9.0
        with:
          local: build/libs/
          remote: ${{ inputs.deploy-path }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

  release:
    needs: build
    if: inputs.release == true
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ github.event.pull_request.number && 'pr-' || 'branch-' }}${{ github.event.pull_request.number || github.ref_name }}"
          commit: ${{ github.event.pull_request.base.ref || github.ref_name }}
          name: "${{ github.event.pull_request.number && 'PR #' }}${{ github.event.pull_request.number || github.ref_name }}"
          body: "Automated release for ${{ github.event.pull_request.number && 'PR #' || 'branch ' }}${{ github.event.pull_request.number || github.ref_name }}."
          artifacts: build/libs/*.jar
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: ${{ inputs.latest }}